output_dir: "result/"

log_settings:
  HDFS:
    log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"
    regex:
      - r"blk_-?\d+"
      - r"(\d+\.){3}\d+(:\d+)?"
    st: 0.5
    depth: 4
  Hadoop:
    log_format: "<Date> <Time> <Level> [<Process>] <Component>: <Content>"
    regex:
      - r"(\d+\.){3}\d+"
    st: 0.5
    depth: 4
  Spark:
    log_format: "<Date> <Time> <Level> <Component>: <Content>"
    regex:
      - r"(\d+\.){3}\d+"
      - r"\b[KGTM]?B\b"
      - r"([\w-]+\.){2,}[\w-]+"
    st: 0.5
    depth: 4
  Zookeeper:
    log_format: "<Date> <Time> - <Level>  [<Node>:<Component>@<Id>] - <Content>"
    regex:
      - r"(/|)(\d+\.){3}\d+(:\d+)?"
    st: 0.5
    depth: 4
  BGL:
    log_format: "<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>"
    regex:
      - r"core\.\d+"
    st: 0.5
    depth: 4
  HPC:
    log_format: "<LogId> <Node> <Component> <State> <Time> <Flag> <Content>"
    regex:
      - r"=\d+"
    st: 0.5
    depth: 4
  Thunderbird:
    log_format: "<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>([<PID>])?: <Content>"
    regex:
      - r"(\d+\.){3}\d+"
    st: 0.5
    depth: 4
  Windows:
    log_format: "<Date> <Time>, <Level>                  <Component>    <Content>"
    regex:
      - r"0x.*?\s"
    st: 0.7
    depth: 5
  Linux:
    log_format: "<Month> <Date> <Time> <Level> <Component>([<PID>])?: <Content>"
    regex:
      - r"(\d+\.){3}\d+"
      - r"\d{2}:\d{2}:\d{2}"
    st: 0.39
    depth: 6
  Android:
    log_format: "<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>"
    regex:
      - r"(/[\w-]+)+"
      - r"([\w-]+\.){2,}[\w-]+"
      - r"\b(\-?\+?\d+)\b|\b0[Xx][a-fA-F\d]+\b|\b[a-fA-F\d]{4,}\b"
    st: 0.2
    depth: 6
  HealthApp:
    log_format: "<Time>|<Component>|<Pid>|<Content>"
    regex: []
    st: 0.2
    depth: 4
  Apache:
    log_format: "[<Time>] [<Level>] <Content>"
    regex:
      - r"(\d+\.){3}\d+"
    st: 0.5
    depth: 4
  Proxifier:
    log_format: "[<Time>] <Program> - <Content>"
    regex:
      - r"<\d+\ssec"
      - r"([\w-]+\.)+[\w-]+(:\d+)?"
      - r"\d{2}:\d{2}(:\d{2})*"
      - r"[KGTM]B"
    st: 0.6
    depth: 3
  OpenSSH:
    log_format: "<Date> <Day> <Time> <Component> sshd[<Pid>]: <Content>"
    regex:
      - r"(\d+\.){3}\d+"
      - r"([\w-]+\.){2,}[\w-]+"
    st: 0.6
    depth: 5
  OpenStack:
    log_format: "<Logrecord> <Date> <Time> <Pid> <Level> <Component> [<ADDR>] <Content>"
    regex:
      - r"((\d+\.){3}\d+,?)+"
      - r"/.+?\s"
      - r"\d+"
    st: 0.5
    depth: 5
  Mac:
    log_format: "<Month>  <Date> <Time> <User> <Component>[<PID>]( (<Address>))?: <Content>"
    regex:
      - r"([\w-]+\.){2,}[\w-]+"
    st: 0.7
    depth: 6