ratio: 1
threshold: 0.1
separator: " "
output_dir: "result/"
# regex:
#   - r'([\w-]+\.)+[\w-]+(:\d+)'  # URL
#   - r'(/|)([0-9]+\.){3}[0-9]+(:[0-9]+|)(:|)'  # IP
#   - r'(?<=[^A-Za-z0-9])(\-?\+?\d+)(?=[^A-Za-z0-9])|[0-9]+$'  # Numbers

log_settings:
  HDFS:
    log_format: '<Date> <Time> <Pid> <Level> <Component>: <Content>'
    regex:
      - r'blk_-?\d+'
      - r'(\d+\.){3}\d+(:\d+)?'
  Android:
    log_format: '<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>'
    regex:
      - r'(/[\w-]+)+'
      - r'([\w-]+\.){2,}[\w-]+'
      - r'\b(\-?\+?\d+)\b|\b0[Xx][a-fA-F\d]+\b|\b[a-fA-F\d]{4,}\b'
  Spark:
    log_format: '<Date> <Time> <Level> <Component>: <Content>'
    regex:
      - r'(\d+\.){3}\d+'
      - r'\b[KGTM]?B\b'
      - r'([\w-]+\.){2,}[\w-]+'
  Zookeeper:
    log_format: '<Date> <Time> - <Level>  [<Node>:<Component>@<Id>] - <Content>'
    regex:
      - r'(/|)(\d+\.){3}\d+(:\d+)?'
  Windows:
    log_format: '<Date> <Time>, <Level>                  <Component>    <Content>'
    regex:
      - r'0x.*?\s'
  Thunderbird:
    log_format: '<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>([<PID>])?: <Content>'
    regex:
      - r'(\d+\.){3}\d+'
  Apache:
    log_format: '[<Time>] [<Level>] <Content>'
    regex:
      - r'(\d+\.){3}\d+'
  BGL:
    log_format: '<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>'
    regex:
      - r'core\.\d+'
  Hadoop:
    log_format: '<Date> <Time> <Level> [<Process>] <Component>: <Content>'
    regex:
      - r'(\d+\.){3}\d+'
  HPC:
    log_format: '<LogId> <Node> <Component> <State> <Time> <Flag> <Content>'
    regex:
      - r'=\d+'
  Linux:
    log_format: '<Month> <Date> <Time> <Level> <Component>([<PID>])?: <Content>'
    regex:
      - r'(\d+\.){3}\d+'
      - r'\d{2}:\d{2}:\d{2}'
  Mac:
    log_format: '<Month>  <Date> <Time> <User> <Component>[<PID>]( (<Address>))?: <Content>'
    regex:
      - r'([\w-]+\.){2,}[\w-]+'
  OpenSSH:
    log_format: '<Date> <Day> <Time> <Component> sshd[<Pid>]: <Content>'
    regex:
      - r'(\d+\.){3}\d+'
      - r'([\w-]+\.){2,}[\w-]+'
  OpenStack:
    log_format: '<Logrecord> <Date> <Time> <Pid> <Level> <Component> [<ADDR>] <Content>'
    regex:
      - r'((\d+\.){3}\d+,?)+'
      - r'/.+?\s'
      - r'\d+'
  HealthApp:
    log_format: '<Time>|<Component>|<Pid>|<Content>'
    regex: []
  Proxifier:
    log_format: '[<Time>] <Program> - <Content>'
    regex:
      - r'<\d+\ssec'
      - r'([\w-]+\.)+[\w-]+(:\d+)?'
      - r'\d{2}:\d{2}(:\d{2})*'
      - r'[KGTM]B'